### ISSUE TITLE
Add more DEA servers

### ISSUE THREAD

**Issue by PanosNB** [yudai/cf_nise_installer#147]
Hello,

Is it possible to add more DEA servers and control their allocated resources? If yes, how would this be done?

I've found a solution for the Bosh installer of Cloudfoundry (https://github.com/cloudfoundry-community/bosh-cloudfoundry/blob/master/tutorials/activities/add-more-deas.md) but I don't know how it would apply to our case. Any help on this please?

**Comment by yudai** [comment]
Hi @PanosNB, unfortunately, you cannot add DEA servers using this installer because it doesn't support clustering. The number of DEA servers is always 1.

If you want to assign more resource to your devbox, you can modify your Vagrantfile. For example, you can assign more memory by modifying this line (https://github.com/yudai/cf_nise_installer/blob/master/Vagrantfile#L12).

**Comment by PanosNB** [comment]
Thank you for your reply @yudai!
